name: github actions
on: [push]
jobs:
  merge_branch:
    name: merge the branch3 to branch4
    runs-on: ubuntu-latest
    steps:
      - name: merge code
        run: |
          git clone https://github.com/mail2sebastianpeter/Actiontest.git
          cd Actiontest
          git checkout branch4
          git merge branch3
    
     
